apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  KAGGLE_USERNAME: ZmxhbWVzb2Rh
  KAGGLE_KEY: S0dBVF82NGRlOTJiOGM0ODVmNWJlZjNiMmUzZTJjM2I3MTY3MA==
  DB_PASSWORD: U3RlaW5zO0dhdGU=